/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as MainLayoutIndexImport } from './routes/_mainLayout.index'
import { Route as MainLayoutAboutImport } from './routes/_mainLayout.about'
import { Route as MainLayoutCategoryImport } from './routes/_mainLayout.$category'

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutIndexRoute = MainLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutAboutRoute = MainLayoutAboutImport.update({
  path: '/about',
  getParentRoute: () => MainLayoutRoute,
} as any)

const MainLayoutCategoryRoute = MainLayoutCategoryImport.update({
  path: '/$category',
  getParentRoute: () => MainLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_mainLayout': {
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/$category': {
      preLoaderRoute: typeof MainLayoutCategoryImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/about': {
      preLoaderRoute: typeof MainLayoutAboutImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/': {
      preLoaderRoute: typeof MainLayoutIndexImport
      parentRoute: typeof MainLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  MainLayoutRoute.addChildren([
    MainLayoutCategoryRoute,
    MainLayoutAboutRoute,
    MainLayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
